import './globals.css'
import { Inter } from 'next/font/google'
import ProviderWrapper from './provider'
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wesellrestaurants::  Restaurant for Sale',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: any) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href='/spoonTranparent (1).ico' sizes="16x16" />
      </head>
      <body className={inter.className}>
      <ProviderWrapper>
            {children}
      </ProviderWrapper>
      </body>
    </html>
  )
}
