import React from 'react';
import style from "./PrivacyPolicy.module.scss";

export default function PrivacyPolicy() {
  return (
    <div className={style.PrivacyPolicy}>
      <div className="container">
        <div className={style.PrivacyPolicyInner}>
          <h2>Privacy Policy</h2>
          <div className={style.PolicyContent}>
            <div className={style.txt}>
              <p>
              At We Sell Restaurants®, we respect and protect the privacy of our customers and those who use our website. This privacy statement provides details about how your personal information is collected and used. Personal information is any information that identifies you or would enable someone to contact you, such as your name, email address, phone number and other non-public information that is associated with the foregoing. This privacy statement applies to the We Sell Restaurants website. We Sell Restaurants, Inc. is located at 6 Meridian Home Ln. Suite 101, Palm Coast Florida 32136. 
              </p>
              <p className={style.redTxt}><b>Information Collection and Use by Us</b></p>
              <p>We are the sole owner of information collected on the website and will not sell, share, or rent this information to others in ways different from what is disclosed in this privacy statement. That includes information provided ruing the voluntary registration process or when you call or email us. We collect information only as necessary to fulfill the purposes set forth in this privacy statement. Our website offers several opportunities for visitors to register for access to restaurant listings for sale, promotional and informational mailings, online resources, and to evaluate our products and services. These registration forms enable users to opt-in to our mailing lists and require users to give contact information (such as name and email address). Notice is given at the point of collection to enable users to choose whether or not they consent to the usage terms. Those who have signed up for future mailings and subsequently wish to withdraw their participation may opt-out of receiving future mailings at any time (see the "Choice/Opt-out" section below). We may use this information to provide you with requested information on our listings, to tailor the presentation of products or services to you, to facilitate your movement through the website or to do better job of marketing or communicating with you. We keep track of activity on our Website using log files stored on our web servers. We collect information, such as IP address, browser type and version, and pages you view. We also keep track of how you got to our Website and any links you click on to leave our Website. We may gather information about any device or other method of communication you use to interact with the Website. We also gather aggregated tracking information regarding overall usage of the Website and the products and services, including tallies of page views and click-through activity and the number of inquiries made. We may use this information to assist us in offering you a personalized Web experience, to assist you with technical support, to diagnose problems with our server, in connection with our security program, to administer our website, to improve our products and services and do a better job of marketing them, or to tailor our product and service offerings to you. </p>
              <p className={style.redTxt}><b>Security and Privacy </b></p>
              <p>We employ reasonable technical, administrative and physical safeguards to protect the confidentiality and security of your personal information. We use industry-recognized technical safeguards, such as firewalls, and have adopted and implemented security procedures to protect your information from loss, misuse or unauthorized alteration. Notwithstanding our efforts, we cannot guarantee absolute or unqualified protection of this information given the open nature and resulting instability of the Internet and World Wide Web, and we make no representations or warranties as to the effectiveness of our security and assume no liability for security breaches or any failure in the security of your computer equipment, your internet service provider or other networks and communications providers. </p>
              <p className={style.redTxt}><b>Sharing of Information</b></p>
              <p>We will never sell or rent your personal information to third parties for their use without your consent. If we are involved in a merger, acquisition, a sale of all or a substantial portion of our assets, or other similar transaction, your information may be transferred as part of that transaction. We will notify you by email and/or a prominent notice on our website of any such transaction and the choices you may have regarding your information. Lastly, we may disclose your personal information to courts, law enforcement authorities and/or other relevant third parties, such as internet service providers, when such disclosure is necessary or advisable, in our sole discretion, to conduct an investigation, respond to a third party or law enforcement subpoena or court order, bring legal action or pursue other relief when you or a third party are or may be: (a) violating our terms and conditions of use; (b) causing injury or other harm to, or otherwise violating our property or other legal rights, or those of other users or third parties; or (c) violating federal, state, local, or other applicable law. This disclosure may include transferring information to the U.S. and outside the European Economic Area.</p>
              <p className={style.redTxt}><b>Cookies</b></p>
              <p>We use a variety of technologies on our website. Among these are cookies: a text-only string of information that a website transfers to the cookie file of the browser on your computer so that the website can remember your browser in the future. A cookie will typically contain the name of the domain from which the cookie has come, the "lifetime" of the cookie, and a value, usually a unique number. When you visit our Website, open our email, encounter our services online, or click on one of our banner ads, we may send you a cookie. Cookies may be used by us in many ways: they allow us to verify the login status of customers using products or services linked directly with our Website, track and measure the success of a particular marketing campaign, and to provide you with more relevant content. Cookies also allow us to track overall site usage and determine areas users prefer, as well as enable us to make your visit to our website easier by recognizing you when you return and help to provide you with a customized experience.</p>
              <p className={style.redTxt}><b>SMS Privacy Policy</b></p>
              <p>By providing your phone number to We Sell Restaurants, you are agreeing to receive text notifications, even if your mobile number is registered on any state or federal do-not-call list. Message frequency varies. Consent is not a condition of purchase.</p>
              <p>If you wish to unsubscribe from receiving text marketing messages and notifications, reply with STOP to any mobile message sent from us or use the unsubscribe link we provided you within any of our messages. You understand and agree that alternative methods of opting out, such as using alternative words or requests, will not be considered a reasonable means of opting out. We do not charge for the service, but you are responsible for all charges and fees associated with text messaging imposed by your wireless provider. Message and data rates may apply.</p>
              <p className={style.redTxt}><b>Choice/Opt-out</b></p>
              <p>Our Anti-Spam Policy tolerates only permission-based email. You may choose to opt-out or select your email preferences when you sign-up for our email lists. You always have the opportunity to opt-out or change preferences by following a link in the footer of all non-transactional email messages sent by us or by emailing us at info@wesellrestaurants.com. If you believe that you have received an unsolicited commercial email from us, please contact us immediately. </p>
              <p className={style.redTxt}><b>Access to Personal Information</b></p>
              <p>You can update your account information, including your email address, by logging in and then clicking on the Account Home Icon in the top right corner of the website. Account information, such as your username and password, can be changed by logging in and then clicking on the My Account Home Icon at the top of page. If you would like to deactivate your account or obtain further information about or access to your personal information, you can do so by contacting customer support by email at info@wesellrestaurants.com or by telephone at (888) 814-8225 if you are located in the U.S. We will retain your information for as long as your account is active or as needed to provide you services. If you wish to cancel your account or request that we no longer use your information to provide you services contact us at info@wesellrestaurants.com. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes and enforce our agreements. </p>
              <p className={style.redTxt}><b>Children </b></p>
              <p>Our Website and our products and services are not directed to persons under 13. We do not knowingly collect personally identifiable information from children under 13. If a parent or guardian becomes aware that his or her child has provided us with personal information without such parent or guardian's consent, he or she should contact us. If we become aware that a child under 13 has provided us with personal information, we will delete such information from our files.</p>
              <p className={style.redTxt}><b>International Use</b></p>
              <p>We are headquartered in the United States of America. We will protect the privacy and security of personal information according to this privacy statement, regardless of where it is processed or stored, however you explicitly acknowledge and consent to the fact that personal information stored or processed in the United States will be subject to the laws of the United States, including the ability of governments, courts or law enforcement or regulatory agencies of the United States to obtain disclosure of your personal information. </p>
              <p className={style.redTxt}><b>Accountability</b></p>
              <p>We have designated our Chief Marketing Officer to oversee our compliance with applicable privacy laws. Questions and inquiries concerning your privacy may be directed by email to robin@wesellrestaurants.com or write us:</p>
              <p>We Sell Restaurants, Inc. 6 Meridian Home Ln. Suite 101 Palm Coast, FL 32137 Attention: Privacy Manager.</p>
              <p className={style.redTxt}><b>Notification of Changes</b></p>
              <p>We reserve the right to modify this privacy statement at any time, so please review it frequently. If we decide to change this privacy statement in any material way, we will notify you here, by email, or by means of a notice on the We Sell Restaurants website so our users are always aware of what information we collect, how we use it and under what circumstances, if any, we disclose it. For major changes in how we use personally identifying data, we will provide advance notice. In all cases, your continued use of any Site or our products and services or constitutes consideration and your binding acceptance to any such change. </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
